"""remove stock from items

Revision ID: a01a0539b1f8
Revises: 21b96f98d5c3
Create Date: 2025-06-04 09:57:32.557266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a01a0539b1f8'
down_revision: Union[str, None] = '21b96f98d5c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
