"""Replace type/type2 with type3

Revision ID: bfbaee726551
Revises: 3ff9873af879
Create Date: 2025-06-12 15:35:40.758806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfbaee726551'
down_revision: Union[str, None] = '3ff9873af879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('type3', sa.Integer(), nullable=True))
    op.drop_column('users', 'type2')
    op.drop_column('users', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('type2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'type3')
    # ### end Alembic commands ###
