name: Deploy Backend

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        run: gcloud auth configure-docker europe-central2-docker.pkg.dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Show secrets for debug
        run: |
          echo "GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}"
          echo "GCP_BACKEND_REPO=${{ secrets.GCP_BACKEND_REPO }}"
          echo "GCP_BACKEND_SERVICE=${{ secrets.GCP_BACKEND_SERVICE }}"
          echo "GCP_REGION=${{ secrets.GCP_REGION }}"

      - name: Build & push image
        run: |
          docker buildx build --platform linux/amd64 --tag europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_BACKEND_REPO }}/backend:latest --push ./backend

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.GCP_BACKEND_SERVICE }} \
            --image europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_BACKEND_REPO }}/backend:latest \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated \
            --port 8000 \
            --add-cloudsql-instances=${{ secrets.GCP_PROJECT_ID }}:${{ secrets.GCP_REGION }}:myapp-postgres \
            --update-secrets "DATABASE_URL=DATABASE_URL_PROD:latest"