name: Deploy Backend

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker Auth
        run: gcloud auth configure-docker europe-central2-docker.pkg.dev

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Debug image path
        run: |
          echo "Project ID: ${{ secrets.GCP_PROJECT_ID }}"
          echo "Backend Repo: ${{ secrets.GCP_BACKEND_REPO }}"
          echo "Image: europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_BACKEND_REPO }}/backend:latest"

      - name: Validate secrets
        run: |
          test -n "${{ secrets.GCP_PROJECT_ID }}" || (echo "Missing GCP_PROJECT_ID" && exit 1)
          test -n "${{ secrets.GCP_BACKEND_REPO }}" || (echo "Missing GCP_BACKEND_REPO" && exit 1)

      - name: Build & Push Docker Image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --tag europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_BACKEND_REPO }}/backend:latest \
            --push \
            ./backend

      - name: Run Alembic migrations
        env:
          DATABASE_URL: postgresql+asyncpg://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}
          IMAGE: europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_BACKEND_REPO }}/backend:latest
        run: |
          echo "IMAGE length: ${#IMAGE}"
          echo "DATABASE_URL length: ${#DATABASE_URL}"
          echo "Running Alembic on $IMAGE"
          docker run --rm \
            -e DATABASE_URL="$DATABASE_URL" \
            -w /app \
            "$IMAGE" \
            alembic upgrade head

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.GCP_BACKEND_SERVICE }} \
            --image europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_BACKEND_REPO }}/backend:latest \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated \
            --port 8080