name: Deploy Backend

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Write GCP SA Key to File
        run: echo "${{ secrets.GCP_SA_KEY }}" > gcp-key.json

      - name: Set GOOGLE_APPLICATION_CREDENTIALS
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/gcp-key.json" >> $GITHUB_ENV

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker Auth
        run: gcloud auth configure-docker europe-central2-docker.pkg.dev

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start Cloud SQL Proxy
        run: |
          echo "Downloading Cloud SQL Proxy..."
          curl -sSfL -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.10.0/cloud-sql-proxy.linux.amd64
          chmod +x cloud-sql-proxy
          echo "Starting Cloud SQL Proxy for instance: ${{ secrets.DB_INSTANCE_CONNECTION_NAME }}"
          ./cloud-sql-proxy --credentials-file=gcp-key.json \
            --port=5432 ${{ secrets.DB_INSTANCE_CONNECTION_NAME }} > proxy.log 2>&1 &

          echo "Waiting for port 5432..."
          for i in {1..15}; do
            nc -z 127.0.0.1 5432 && echo "Cloud SQL Proxy is ready" && break
            echo "Still waiting for Cloud SQL Proxy on 127.0.0.1:5432... ($i/15)"
            sleep 1
          done

          echo "== Proxy Logs =="
          cat proxy.log || true

      - name: Build & Push Docker Image
        run: |
          echo "Building Docker image..."
          docker buildx build \
            --platform linux/amd64 \
            --tag europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_BACKEND_REPO }}/backend:latest \
            --push \
            ./backend

      - name: Run Alembic migrations
        env:
          DATABASE_URL: postgresql+asyncpg://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@127.0.0.1:5432/${{ secrets.DB_NAME }}
          IMAGE: europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_BACKEND_REPO }}/backend:latest
        run: |
          echo "DATABASE_URL: $DATABASE_URL"
          echo "Using image: $IMAGE"
          echo "Running Alembic upgrade..."
          docker run --rm \
            -e DATABASE_URL="$DATABASE_URL" \
            -w /app \
            "$IMAGE" \
            alembic upgrade head || { echo "Alembic failed"; exit 1; }

      - name: Deploy to Cloud Run
        run: |
          echo "Deploying to Cloud Run..."
          gcloud run deploy ${{ secrets.GCP_BACKEND_SERVICE }} \
            --image europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_BACKEND_REPO }}/backend:latest \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated \
            --port 8080