name: Deploy Frontend

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        run: gcloud auth configure-docker europe-central2-docker.pkg.dev

      - name: Debug Environment and Paths
        run: |
          set -x
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "Secrets:"
          echo "GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}"
          echo "GCP_FRONTEND_REPO=${{ secrets.GCP_FRONTEND_REPO }}"
          echo "GCP_FRONTEND_SERVICE=${{ secrets.GCP_FRONTEND_SERVICE }}"
          echo "GCP_REGION=${{ secrets.GCP_REGION }}"
          echo "Current Directory:"
          pwd
          echo "Contents of ./frontend:"
          ls -la ./frontend

      - name: Reset Docker builder to legacy
        run: |
          docker buildx stop || true
          docker buildx rm default || true

      - name: Build Docker Image
        run: |
          set -x
          docker build -t europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_FRONTEND_REPO }}/frontend:latest ./frontend

      - name: Push Docker Image
        run: |
          set -x
          docker push europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_FRONTEND_REPO }}/frontend:latest

      - name: Deploy to Cloud Run
        run: |
          set -x
          gcloud run deploy ${{ secrets.GCP_FRONTEND_SERVICE }} \
            --image europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_FRONTEND_REPO }}/frontend:latest \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated \
            --port 80