name: Deploy Frontend

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker Auth
        run: gcloud auth configure-docker europe-central2-docker.pkg.dev

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Debug Secrets and Paths
        run: |
          echo "GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}"
          echo "GCP_FRONTEND_REPO=${{ secrets.GCP_FRONTEND_REPO }}"
          echo "GCP_FRONTEND_SERVICE=${{ secrets.GCP_FRONTEND_SERVICE }}"
          echo "GCP_REGION=${{ secrets.GCP_REGION }}"
          echo "Workspace:"
          ls -la $GITHUB_WORKSPACE
          echo "Frontend folder:"
          ls -la $GITHUB_WORKSPACE/frontend

      - name: Build & Push Docker Image
        run: |
          docker buildx build --platform linux/amd64 \
            --tag europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_FRONTEND_REPO }}/frontend:latest \
            --push \
            ./frontend

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.GCP_FRONTEND_SERVICE }} \
            --image europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_FRONTEND_REPO }}/frontend:latest \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated \
            --port 80